name: "Run Extension Tests"

on:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    name: Run VS Code Extension Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and run tests
        # Github actions is a headless enviroment, so we need to run tests on a virtual display
        run: |
          npm install
          npm run test
